// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v7.34.0
// source: users.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "users";

export interface User {
  id: number;
  name: string;
  age: number;
}

export interface GetFilteredUsersRequest {
}

export interface GetFilteredUsersResponse {
  users: User[];
}

export const USERS_PACKAGE_NAME = "users";

export interface UserServiceClient {
  getFilteredUsers(request: GetFilteredUsersRequest): Observable<GetFilteredUsersResponse>;
}

export interface UserServiceController {
  getFilteredUsers(
    request: GetFilteredUsersRequest,
  ): Promise<GetFilteredUsersResponse> | Observable<GetFilteredUsersResponse> | GetFilteredUsersResponse;
}

export function UserServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["getFilteredUsers"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("UserService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("UserService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const USER_SERVICE_NAME = "UserService";
